### ISSUE TITLE
Can not install ASCAT package

### ISSUE THREAD

**Issue by DecodeGenome** [ShixiangWang/gcap#42]
Hi I have issue to install ASCAT following your guideline.
remotes::install_github("ShixiangWang/ascat@v3-for-gcap-v1", subdir = "ASCAT")
Using GitHub PAT from the git credential store.
Error: Failed to install 'ASCAT' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 58/60
  Rate limit reset at: 2024-04-28 05:40:22 UTC

**Comment by ShixiangWang** [comment]
Network issue. You can download it https://github.com/ShixiangWang/ascat/releases to local and install it
