### ISSUE TITLE
What kind of .bam file is more recommended?

### ISSUE THREAD

**Issue by CC-DrDU** [ShixiangWang/gcap#44]
Hi Shixiang,

First of all I would like to thank you for your excellent work which provide a special technique on analyzing WES data. I wish to consult you a question. During WES analyse process (for instance, the GATK best practice of paired tumor-normal mutation calling), we are expected to get a series of .bam files after aligning and sorting (.sorted.bam), MarkDuplicated (.markdup.bam), and ApplyBQSR (.bqsr.bam). Which .bam file is more recommended for gcap process?

Thank you again and look forward to your reply.

**Comment by ShixiangWang** [comment]
Yes. You can directly use the bam files after ApplyBQSR, as the copy number calling is firstly exeuted for the bams.
