### ISSUE TITLE
Error occured while running GCAP with docker

### ISSUE THREAD

**Issue by CC-DrDU** [ShixiangWang/gcap#46]
Hi Shixiang. It me again hahaha.

In the past few days I tried to run GCAP workflow using docker. However, error occured during Step 1. Here is the issue.

<gcap> 2024-07-31 13:02:46.783007 info [gcap.workflow]: =====================
<gcap> 2024-07-31 13:02:46.861744 info [gcap.workflow]:    GCAP WORKFLOW
<gcap> 2024-07-31 13:02:46.874999 info [gcap.workflow]: =====================
<gcap> 2024-07-31 13:02:46.87687 info [gcap.workflow]:
<gcap> 2024-07-31 13:02:46.878666 info [gcap.workflow]: =====================
<gcap> 2024-07-31 13:02:46.880441 info [gcap.workflow]: Step 1: Run ASCAT 3.0
<gcap> 2024-07-31 13:02:46.882128 info [gcap.workflow]: =====================
<gcap> 2024-07-31 13:02:46.916249 info [gcap.runASCAT]: > Run ASCAT on WES data <
<gcap> 2024-07-31 13:02:46.91948 info [gcap.runASCAT]:
<gcap> 2024-07-31 13:02:46.92314 info [gcap.runASCAT]: Configs:
<gcap> 2024-07-31 13:02:46.926549 info [gcap.runASCAT]:   result path set to /home/dell/WES_LANDSCAPE_2024/GCAP/test_run_gcap/
<gcap> 2024-07-31 13:02:46.928997 info [gcap.runASCAT]:   allelecounter_exe set to /opt/conda/envs/cancerit/bin/alleleCounter
<gcap> 2024-07-31 13:02:46.931258 info [gcap.runASCAT]:   g1000allelesprefix set to /home/dell/WES_LANDSCAPE_2024/GCAP/1000G_loci_hg38/1kg.phase3.v5a_GRCh38nounref_allele_index_chr
<gcap> 2024-07-31 13:02:46.933726 info [gcap.runASCAT]:   g1000lociprefix set to /home/dell/WES_LANDSCAPE_2024/GCAP/1000G_loci_hg38/1kg.phase3.v5a_GRCh38nounref_loci_chrstring_chr
<gcap> 2024-07-31 13:02:46.935469 info [gcap.runASCAT]:   GCcontentfile set to /home/dell//WES_LANDSCAPE_2024/GCAP/GC_correction_hg38.txt
<gcap> 2024-07-31 13:02:46.937241 info [gcap.runASCAT]:   replictimingfile set to /home/dell/WES_LANDSCAPE_2024/GCAP/RT_correction_hg38.txt
<gcap> 2024-07-31 13:02:46.938991 info [gcap.runASCAT]:   nthreads set to 10
<gcap> 2024-07-31 13:02:46.940747 info [gcap.runASCAT]:   minCounts set to 10
<gcap> 2024-07-31 13:02:46.942546 info [gcap.runASCAT]:   BED_file set to /home/dell/WES_LANDSCAPE_2024/S07604514_Regions.bed
<gcap> 2024-07-31 13:02:46.94439 info [gcap.runASCAT]:   probloci_file set to NA
<gcap> 2024-07-31 13:02:46.946275 info [gcap.runASCAT]:   chrom_names set to <1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22>
<gcap> 2024-07-31 13:02:46.948128 info [gcap.runASCAT]:   gender set to <XX>
<gcap> 2024-07-31 13:02:46.949991 info [gcap.runASCAT]:   min_base_qual set to 20
<gcap> 2024-07-31 13:02:46.951839 info [gcap.runASCAT]:   min_map_qual set to 35
<gcap> 2024-07-31 13:02:46.953615 info [gcap.runASCAT]:   penalty set to 70
<gcap> 2024-07-31 13:02:46.956273 info [gcap.runASCAT]:   skip_finished_ASCAT set to FALSE
<gcap> 2024-07-31 13:02:46.960423 info [gcap.runASCAT]: 1 jobs detected
<gcap> 2024-07-31 13:02:46.96337 info [FUN]: start submitting job T17
<gcap> 2024-07-31 13:02:46.966261 info [FUN]:      tumor data file: T17.bqsr.bam
<gcap> 2024-07-31 13:02:46.968438 info [FUN]:     normal data file: 1221.bqsr.bam
<gcap> 2024-07-31 13:02:46.970265 info [FUN]:    tumor sample name: T17
<gcap> 2024-07-31 13:02:46.972052 info [FUN]:   normal sample name: 1221
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
[1] Reading Tumor LogR data...
[1] Reading Tumor BAF data...
[1] Reading Germline LogR data...
[1] Reading Germline BAF data...
[1] Registering SNP locations...
[1] Splitting genome in distinct chunks...
<gcap> 2024-07-31 13:09:39.251546 fatal [value[[3L]]]: job T17 failed in ASCAT due to following error
<gcap> 2024-07-31 13:09:39.28275 info [value[[3L]]]: duplicate row.names: 202201, 234986, 261210, 261972, 266248, 267519, 283190, 294530, 296847, 301442, 320957, 323649, 324170, 338106, 340363, 351265, 357042, 364795, 372700, 372784, 378816, 388922, 391355, 395511, 400220, 408643, 409322, 418601, 435463, 442622, 452738, 454054, 477935, 487979, 492573, 504584, 505006, 531504, 532596, 541737, 558497, 565390, 567196, 568958, 584112, 590316, 595168, 606607, 609081, 612430, 615389, 618675, 632060, 634488, 644168, 649639, 654091, 654229, 666677, 672067, 678561, 679436, 693647, 710763, 711229, 713384, 723197, 727446, 728191, 729033, 729039, 733344, 737030, 737188, 739217, 741912, 744480, 755136, 767078, 771740, 774135, 774982, 780689, 783028, 786660, 788110, 805578, 818986, 822697, 834781, 840319, 869280, 870467, 874501, 883788, 887073, 892135, 907933, 915764, 925845, 933873, 949121, 957245, 973374, 976434, 996522, 998839, 1027546, 1030504, 1034241, 1036573, 1046280, 1053186, 1053659, 1055942, 1070813, 1073377, 1073876, 1082850, 1084537, 1085779, 1087109, 1089638, 1089694, 1090563, 1096268, 1099573, 1107741, 1108678, 1117439, 1118819, 1127749, 1155962, 1159756, 1160526, 1161498, 1162380, 1169182, 1171428, 1175024, 1177190, 1180187, 1181472, 1185655, 1186069, 1197014, 1197482, 1216048, 1220267, 1220554, 1227933, 1229093, 1229573, 1231261, 1232477, 1241088, 1242609, 1242792, 1244721, 1249618, 1253813, 1258530, 1263246, 1266630, 1269349, 1290684, 1293189, 1299719, 1301363, 1323384, 1333005, 1344630, 1351665, 1356854, 1367747, 1369270, 1371344, 1372465, 1380529, 1387501, 1392737, 1393174, 1393455, 1404603, 1409425, 1409853, 1410591, 1413349, 1414359, 1415168, 1425125, 1435101, 1436705, 1439242, 1452851, 1458076, 1459725, 1462214, 1464282, 1465794, 1469278, 1477489, 1479875, 1480404, 1490178, 1491353, 1494802, 1495936, 1496399, 1499386, 1506946, 1508222, 1521324, 1536816, 1552508, 1562907, 1572468, 1573941, 1578949, 1579343, 1584139, 1601272, 1613770, 1615624, 1639574, 1641999, 1642996, 1645916, 1654305, 1656168, 1657489, 1660854, 1668896, 1693365, 1715361, 1722954, 1737985, 1746963, 1748763, 1761066, 1766468, 1788958, 1789074, 1791353, 1794471, 1795392, 1803051, 1813279, 1824552, 1826369, 1833341, 1833342, 1842330, 1847593, 1849552, 1859806, 1860294, 1865135, 1865518, 1868019, 1871874, 1873844, 1874521, 1878167, 1878288, 1879935, 1884062, 1890065, 1891066, 1894278, 1905708, 1914857, 1923624, 1927095, 1927810, 1937086, 1941087, 1941562, 1942797, 1983679, 2042368, 2046402, 2053386, 2066419, 2075657, 2076286, 2080053, 2092368, 2106097, 2113053, 2120535, 2127162, 2131091, 2131924, 2147345, 2155266, 2156357, 2166125, 2168930, 2169245, 2178851, 2187012, 2207545, 2210133, 2211080, 2211584, 2217521, 2223207, 2228353, 2241748, 2248186, 2251065, 2256475, 2259400, 2261495, 2263086, 2275849, 2275888, 2286325, 2294873, 2302074, 2312445, 2312680, 2315988, 2321126, 2327591, 2331767, 2340394, 2345030, 2347994, 2355079, 2358745, 2362171, 2362416, 2372385, 2374291, 2374629, 2378031, 2392980, 2402690, 2406415, 2420046, 2425287, 2430667, 2442814, 2447257, 2448204, 2455392, 2456957, 2459976, 2460509, 2461867, 2479626, 2496079, 2496789, 2499040, 2501312, 2505433, 2506057, 2511008, 2521186, 2531610, 2532111, 2533716, 2536701, 2540377, 2540384, 2544280, 2546586, 2550566, 2553478, 2559968, 2560550, 2562764, 2570182, 2574922, 2581781, 2586744, 2593381, 2598611, 2604369, 2610436, 2611011, 2619296, 2621069, 2622290, 2624755, 2628075, 2659118, 2673812, 2678505, 2687958, 2690861, 2698159, 2700031, 2703028, 2705955, 2709642, 2714175, 2714953, 2726345, 2736797, 2742789, 2743839, 2749558, 2749762, 2750046, 2751549, 2756853, 2760879, 2767228, 2772772, 2774228, 2791411, 2793900, 2815795, 2824973, 2825279, 2827635, 2835198, 2835417, 2835964, 2841615, 2846202, 2848308, 2854827, 2858388, 2860483, 2870472, 2874366, 2884872, 2906321, 2915296, 2918727, 2918997, 2923880, 2929952, 2930838, 2942608, 2954569, 2960486, 2966041, 2977682, 2977945, 2978294, 2979875, 2989410, 2998440, 3026404, 3027277, 3030423, 3032965, 3048607, 3066745, 3071291, 3077316, 3080718, 3082525, 3083346, 3092489, 3097941, 3098024, 3108706, 3112075, 3112330, 3127081, 3127579, 3128167, 3130408, 3130635, 3132707, 3134446, 3142215, 3142975, 3143035, 3143515, 3143561, 3145947, 3152947, 3155875, 3167297, 3172819, 3192928, 3195991, 3196977, 3197479, 3199508, 3201668, 3203133, 3203951, 3204635, 3219972, 3220993, 3223477, 3229565, 3240707, 3340966, 3344912, 3356105, 3357685, 3364672, 3374532, 3381247, 3389232, 3389633, 3399646, 3404224, 3406743, 3411076, 3411793, 3422247, 3444522, 3454812, 3462663, 3464691, 3473392, 3483129, 3498188, 3516078, 3519284, 3519420, 3521126, 3538980, 3541482, 3548086, 3572710, 3572773, 3584202, 3602068, 3606425, 3630114, 3642556, 3643961, 3646462, 3653744, 3653749, 3664892, 3665163, 3680844, 3696091, 3700892, 3710355, 3719130, 3721242, 3731878, 3737780, 3772452, 3775360, 3784605, 3791482, 3792336, 3799288, 3802810, 3804767, 3815176, 3815245, 3815872, 3826200, 3828870, 3849988, 3864719, 3871775, 3884282, 3885777, 3885917, 3902829, 3903969, 3909922, 3913098, 3920771, 3929030, 3932276, 3938037, 3941613, 3943941, 3947374, 3951006, 3979078, 3980849, 3984440, 3998218, 4009713, 4010316, 4017555, 4019777, 4019819, 4027687, 4052809, 4057955, 4074811, 4095591, 4096335, 4103986, 4115744, 4124923, 4129644, 4142023, 4144994, 4165922, 4166535, 4177363, 4180985, 4183851, 4197142, 4217094, 4217539, 4218863, 4220335, 4220373, 4224823, 4240728, 4240746, 4243293, 4243585, 4251964, 4260918, 4265297, 4265315, 4286218, 4286665, 4305522, 4309581, 4310221, 4328080, 4328926, 4339890, 4347761, 4363518, 4370044, 4373189, 4384390, 4389578, 4390887, 4394747, 4400316, 4406890, 4411811, 4412088, 4413985, 4418612, 4422110, 4430592, 4438111, 4441818, 4445612, 4456024, 4463752, 4475686, 4476904, 4485970, 4490135, 4490790, 4494362, 4508073, 4518255, 4531863, 4532610, 4534266, 4536511, 4538333, 4545147, 4545742, 4557300, 4561446, 4562976, 4564697, 4565830, 4569393, 4572101, 4574741, 4576750, 4577876, 4587718, 4607938, 4615444, 4629449, 4639033, 4645580, 4649166, 4649469, 4658102, 4659377, 4661652, 4701944, 4704153, 4708172, 4716553, 4719220, 4734961, 4737470, 4769334, 4769452, 4770845, 4787077, 4798363, 4804816, 4809051, 4815117, 4824036, 4825276, 4830229, 4830640, 4839842, 4851960, 4854543, 4856138, 4856782, 4861525, 4876631, 4884245, 4884901, 4887836, 4890764, 4916649, 4921144, 4931987, 4933161, 4939504, 4939975, 4941522, 4945765, 4946000, 4950297, 4958996, 4961358, 4964813, 4976802, 4979155, 4982862, 4989685, 5001199, 5007910, 5009623, 5014959, 5022125, 5022321, 5026860, 5031935, 5033871, 5045379, 5052137, 5060832, 5063031, 5063925, 5064141, 5069221, 5069409, 5076650, 5077834, 5081991, 5083887, 5102777, 5103241, 5104510, 5104799, 5106384, 5107193, 5109804, 5127524, 5139344, 5158833, 5159781, 5167706, 5175201, 5175734, 5178415, 5182988, 5183359, 5185908, 5186366, 5192235, 5193799, 5198087, 5199393, 5210736, 5211675, 5221740, 5222165, 5222396, 5222687, 5231804, 5237035, 5237210, 5241613, 5245229, 5252486, 5252635, 5276723, 5285749, 5287818, 5293310, 5294668, 5294765, 5294851, 5300431, 5312714, 5313482, 5317177, 5320670, 5326635, 5338701, 5343066, 5346185, 5350095, 5352992, 5356260, 5358536, 5370828, 5373020, 5377527, 5377657, 5377758, 5378514, 5380445, 5381239, 5383153, 5383317, 5389024, 5392057, 5395463, 5398439, 5401160, 5407194, 5413345, 5419412, 5423654, 5440875, 5461647, 5471030, 5476516, 5483919, 5492424, 5494016, 5497965, 5505181, 5506677, 5512540, 5515079, 5519518, 5526457, 5527547, 5533056, 5542902, 5556466, 5574696, 5577013, 5577508, 5588337, 5592501, 5601556, 5602207, 5602251, 5604021, 5615875, 5621094, 5635375, 5640915, 5645225, 5648502, 5649761, 5663657, 5670124, 5677989, 5678854, 5680653, 5684521, 5691617, 5696871, 5710669, 5718392, 5753611, 5753612, 5754133, 5756599, 5766123, 5772287, 5774736, 5785111, 5804124, 5805654, 5809501, 5821338, 5872618, 5873149, 5874238, 5874866, 5878655, 5882519, 5884227, 5884932, 5885875, 5887748, 5892683, 5904285, 5912983, 5913239, 5913328, 5921914, 5926212, 5938022, 5950470, 5952237, 5961349, 5978905, 5995033, 5996209, 5997991, 6007468, 6013882, 6020952, 6024498, 6027085, 6033248, 6037520, 6051838, 6052295, 6057345, 6057770, 6058176, 60731
<gcap> 2024-07-31 13:09:39.286844 info [value[[3L]]]: =====
<gcap> 2024-07-31 13:09:39.289119 info [value[[3L]]]: Please check your input bam files (if missing bam index? if its alignment quality is lower?)
<gcap> 2024-07-31 13:09:39.291706 info [value[[3L]]]: =====

I guess there was something wrong with my .bam files, although I have provided the corresponding index file and those .bam files were succesfully used for the usual WES workflow.

Anyways, I will try again using R directly, but could you please let if you have any clue about this issue? Thank you and your remarkable work!

**Comment by ShixiangWang** [comment]
Based on the error, this is probably an issue related to reference files you are using. Please take a deep look at https://github.com/ShixiangWang/gcap?tab=readme-ov-file#install-ascat-required

**Comment by ShixiangWang** [comment]
glad to hear that
