### ISSUE TITLE
<gcap> 2024-08-07 00:38:13 info [value[[3L]]]: duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by GetOutofBug** [ShixiangWang/gcap#47]
[1] Reading Tumor LogR data...
[1] Reading Tumor BAF data...
[1] Reading Germline LogR data...
[1] Reading Germline BAF data...
[1] Registering SNP locations...
[1] Splitting genome in distinct chunks...
<gcap> 2024-08-07 00:38:13 fatal [value[[3L]]]: job SYS-01 failed in ASCAT due to following error                  
<gcap> 2024-08-07 00:38:13 info [value[[3L]]]: duplicate 'row.names' are not allowed
<gcap> 2024-08-07 00:38:13 info [value[[3L]]]: =====
<gcap> 2024-08-07 00:38:13 info [value[[3L]]]: Please check your input bam files (if missing bam index? if its alignment quality is lower?)
<gcap> 2024-08-07 00:38:13 info [value[[3L]]]: =====
<gcap> 2024-08-07 00:38:13 info [gcap.runASCAT]: ASCAT analysis done, check /lustre/home/0061007054/WES/01ASCAT/01SYS/GCAP for results
Warning messages:
1: One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) 
2: non-unique values when setting 'row.names': ‘pos_NA’, ‘X_100000139’, ‘X_10000024’, ‘X_100000470’, ‘X_100000513’, ‘X_100000572’, ‘X_100000866’, ‘X_100000912’, ‘X_100000958’, ‘X_100001003’, ‘X_100001198’, ‘X_100001240’, ‘X_100001490’, ‘X_100001511’, ‘X_100001623’, ‘X_100001765’, ‘X_100001806’, ‘X_100001808’, ‘X_100001926’, ‘X_100001955’, ‘X_100002091’, ‘X_100002252’, ‘X_100002556’, ‘X_100002721’, ‘X_100002755’, ‘X_100002757’, ‘X_100002797’, ‘X_100003078’, ‘X_100003322’, ‘X_100003423’, ‘X_100003589’, ‘X_100003631’, ‘X_100003723’, ‘X_100003793’, ‘X_100004047’, ‘X_100004060’, ‘X_100004233’, ‘X_100004372’, ‘X_100004439’, ‘X_100004611’, ‘X_100004742’, ‘X_100004865’, ‘X_100005100’, ‘X_100005151’, ‘X_100005278’, ‘X_100005457’, ‘X_100005630’, ‘X_100005768’, ‘X_100005935’, ‘X_100006047’, ‘X_1000062 [... truncated] 

Why do duplicate values occur? I don't know how to solve this problem...

**Comment by ShixiangWang** [comment]
Hi @GetOutofBug , thanks for trying the gcap. This error typically caused by unmatched file reading. Did you use the latest version of ASCAT and its reference files?

<img width="739" alt="image" src="https://github.com/user-attachments/assets/47aed0f5-37d3-4d4a-a86f-b488a99aabeb">

**Comment by GetOutofBug** [comment]
Thanks for your reply! There were a lot of bugs when I used version 3.1.3, so my current package Version of ASCAT is 3.0.0. I also think it's a matching file problem. The GC and RT files that I downloaded are made up of different chromosomes, and I merge them together, and I think that's the problem. Do you have the URL to download the RT_correction_hg38.txt and GC_correction_hg38.txt files directly? Thank you so much!

**Comment by GetOutofBug** [comment]
It's me. I checked the file, and there are duplicate values.

tail -n +2 RT_correction_hg38.txt | grep -Fx "$(head -n 1 RT_correction_hg38.txt)"
chr	pos	Bg02es	Bj	Gm06990	Gm12801	Gm12812	Gm12813	Gm12878	Helas3	Hepg2	Huvec	Imr90	K562	Mcf7	Nhek	Sknsh
chr	pos	Bg02es	Bj	Gm06990	Gm12801	Gm12812	Gm12813	Gm12878	Helas3	Hepg2	Huvec	Imr90	K562	Mcf7	Nhek	Sknsh

After I re-processed the two data and confirmed that there were no duplicate rows, I ran gcap.runASCAT again, but the same error still appeared.

Reading locis
Done reading locis
Multi pos start:
[1] Reading Tumor LogR data...
[1] Reading Tumor BAF data...
[1] Reading Germline LogR data...
[1] Reading Germline BAF data...
[1] Registering SNP locations...
[1] Splitting genome in distinct chunks...
<gcap> 2024-08-07 12:29:24 fatal [value[[3L]]]: job SYS-01 failed in ASCAT due to following error                  
<gcap> 2024-08-07 12:29:24 info [value[[3L]]]: duplicate 'row.names' are not allowed
<gcap> 2024-08-07 12:29:24 info [value[[3L]]]: =====
<gcap> 2024-08-07 12:29:24 info [value[[3L]]]: Please check your input bam files (if missing bam index? if its alignment quality is lower?)
<gcap> 2024-08-07 12:29:24 info [value[[3L]]]: =====
<gcap> 2024-08-07 12:29:24 info [gcap.runASCAT]: ASCAT analysis done, check /lustre/home/0061007054/WES/01ASCAT/01SYS/GCAP for results

**Comment by GetOutofBug** [comment]
If I upgrade the version of ASCAT to 3.1.3, I get the following error:

<gcap> 2024-08-07 12:38:18 fatal [value[[3L]]]: job SYS-01 failed in ASCAT due to following error
<gcap> 2024-08-07 12:38:18 info [value[[3L]]]: unused arguments (g1000allelesprefix = g1000allelesprefix, g1000lociprefix = g1000lociprefix)
<gcap> 2024-08-07 12:38:18 info [value[[3L]]]: =====
<gcap> 2024-08-07 12:38:18 info [value[[3L]]]: Please check your input bam files (if missing bam index? if its alignment quality is lower?)
<gcap> 2024-08-07 12:38:18 info [value[[3L]]]: =====

**Comment by GetOutofBug** [comment]
Thank you for your reply. I solved this error by downloading the correct RT and GC files.
