### ISSUE TITLE
 identical(allele_data[, 1], tumour_input_data[, 1]) && identical(allele_data[,  .... is not TRUE

### ISSUE THREAD

**Issue by GetOutofBug** [ShixiangWang/gcap#48]
If I set only one bam file as input, normalseqfile = NA, I get this error. Is it because gcap.runASCAT can't run a single sample?

<gcap> 2024-08-08 12:04:47 fatal [value[[3L]]]: job SYS failed in ASCAT due to following error
<gcap> 2024-08-08 12:04:47 info [value[[3L]]]: identical(allele_data[, 1], tumour_input_data[, 1]) && identical(allele_data[,  .... is not TRUE
<gcap> 2024-08-08 12:04:47 info [value[[3L]]]: =====
<gcap> 2024-08-08 12:04:47 info [value[[3L]]]: Please check your input bam files (if missing bam index? if its alignment quality is lower?)

**Comment by ShixiangWang** [comment]
Yeah. Only paired samples are suported.

**Comment by GetOutofBug** [comment]
Thank you very much!
